from snakemake.utils import min_version
from pathlib import Path
import os

##### set minimum snakemake version #####
min_version("8.8.0")

configfile: "config.yaml"

##### resolve global paths from data_dir for input and databases #####
base = Path(config["data_dir"])

config["samples"] = str(base / config["samples"])
for k in ("long_reads", "short_reads", "read_qc", "dehost"):
    config["input"][k] = str(base / config["input"][k])

config["reference"]["human"] = str(Path(config["input"]["databases"]) / config["reference"]["human"])

##### Create symlink on startup to dodge CheckM error #####
symlink_path = "m"
target_path = str(base / "hybrid_temp/binning")
if os.path.islink(symlink_path):
    if os.readlink(symlink_path) != target_path:
        os.unlink(symlink_path)
        os.symlink(target_path, symlink_path)
elif os.path.exists(symlink_path):
    if os.path.isdir(symlink_path):
        shutil.rmtree(symlink_path)
    else:
        os.remove(symlink_path)
    os.symlink(target_path, symlink_path)
else:
    os.symlink(target_path, symlink_path)


##### samples #####
with open(config["samples"]) as f:
    next(f)  # skip header
    SAMPLES = [line.split()[0] for line in f if line.strip()]

##### entry point #####
rule all:
    input:     
#        str(base / "hybrid_temp/drep/hybrid/Cdb.csv"),
#        str(base / "result/metawrap_bins/hybrid/hybrid_genomeInfo.csv"),
#        expand("m/{sample}_binning/bin_reassembly/reassembly_results.png", sample=SAMPLES),
#        expand("m/{sample}_binning/bin_refinement/metawrap_70_10_bins.stats", sample=SAMPLES),
        expand("m/{sample}_binning/concoct_bins/bin.1.fa", sample=SAMPLES),
        expand(str(base / config["output"]["assembly"]["binning"] / "{sample}_binning/metabat2_bins/bin.1.fa"), sample=SAMPLES),
        expand(str(base / config["output"]["assembly"]["binning"] / "{sample}_binning/maxbin2_bins/bin.1.fa"), sample=SAMPLES), 
#        expand(str(base / config["output"]["assembly"]["spades"] / "{sample}_assembly" / "contigs.fasta"), sample=SAMPLES), 
#        expand(str(base / config["output"]["qc"]["read_qc"] / "{sample}" / "final_pure_reads_1.fastq"), sample=SAMPLES),
#        expand(str(base / config["output"]["dehost"]["sam"] / "nano.{sample}.dehost.fq.gz"), sample=SAMPLES)

##### load rules #####
#include: "rules/nano_dehost.smk"
#include: "rules/read_qc.smk"
#include: "rules/assembly.smk"
include: "rules/binning.smk"
#include: "rules/bin_refinement.smk"
#include: "rules/reassembly.smk"
#include: "rules/summarize_bins.smk"
#include: "rules/dereplication.smk"
